# OpenAPI linting workflow
name: OpenAPI lint workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "spectral", "demo"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli

      - name: Verify Spectral CLI installation
        run: spectral --version

      - name: Download the latest Spectral Ruleset of the National Interoperability Model
        run: wget https://github.com/italia/api-oas-checker-rules/releases/latest/download/spectral.yml -O spectral.yml

      - name: Spectral lint Specifiche OpenAPI servizi REST
        run: spectral lint docs/openapi/*.yaml -r spectral.yml
